const datahome = [
  {
    id: 1,
    name: "Lẩu cá chép giòn",
    img: require("./assets/IMG/home/lau-ca-chep-gion-chua-ngot-hai-hoa.png"),
    des: [
      " Món ăn này được chế biến từ cá chép tươi sống",
      " được làm sạch và chiên giòn. Nước lẩu được nấu từ xương cá",
      " xương ống và các loại rau củ quả như cà chua, dứa, măng chua",
      " ... Lẩu cá chép giòn thường được ăn kèm với bún",
      " rau sống và các loại hải sản khác như tôm, cua, mực,...",
    ],
    nguyenlieu: [
      "- 4 lít nước xương hầm\n",
      "- 1 con cá chép giòn\n",
      "- 2 củ hành tây\n",
      "- 1 trái thơm\n",
      "- 3 quả cà chua\n",
      "- Rau ăn lẩu (chuẩn bị tùy theo khẩu phần của gia đình bạn):",
      " Nấm kim châm, bông thiên lý, cải xanh, mồng tơi.\n",
      "- Gia vị: Hành boa rô, sả, ngò gai, thì là, hạt nêm,",
      " đường trắng, nước mắm, sa tế cay, dầu ăn\n",
      "- Bún tươi",
    ],
    buoc1: [
      "- Cá rửa sạch, thái thành từng miếng mỏng vừa ăn,",
      " sau đó ướp với 1 muỗng hạt nêm.\n\n",
      "- Ép nước 1 quả thơm chung với 1 củ hành tây.",
      " 3 quả cà chua rửa sạch và xay nhuyễn.\n\n",
      "- Lấy 1 cây hành và 2 cây sả rửa sạch và băm nhuyễn.",
      " Ngò gai, thì là rửa sạch và cắt",
      " khúc khoảng 1-2cm.\n\n",
      "- Các rau còn lại rửa sạch để cho ráo nước.\n",
    ],
    buoc2: [
      "- Bật bếp để làm nóng nồi, sau đó bỏ 3 muỗng canh dầu ăn vào.",
      " Đợi dầu sôi, cho hành, sả vào phi cho thơm.\n",
      "- Hành, sả chín vàng thì tiếp tục cho cà chua vào xào đến khi chín nẫu,",
      " rồi nêm 2 muỗng hạt nêm, 2 muỗng đường trắng và sa tế vào nồi",
      " (khẩu phần tuỳ theo bạn ăn cay nhiều hay ít).\n",
      "- Đợi đến khi hỗn hợp sệt lại thì để đầu và xương cá vào xào cho thịt săn lại.",
      " Sau đó, đổ nước cốt thơm hành tây và nước xương hầm vào nồi.\n",
    ],
    buoc3: [
      "- Đậy nắp kín lại, đun cho tới khi nước dùng sôi lên thì để",
      " thả hành boa rô, thì là vào cho thơm.\n\n",
      "- Dọn kèm rau, bún ra cùng với lẩu và thưởng thức.\n",
    ],
    type: "Lẩu",
  },
  {
    id: 2,
    name: "Cháo sườn",
    img: require("./assets/IMG/home/chao-suon.png"),
    des: [
      " Cháo sườn được nấu từ gạo và nước",
      " sau đó cho sườn heo vào ninh nhừ. Khi sườn chín mềm",
      " bạn cho các loại gia vị vào nêm cho vừa ăn. Cháo sườn thường",
      " được ăn kèm với hành lá",
      " rau răm, và các loại topping như quẩy, ruốc,...",
    ],
    type: "Cháo", 
  },
  {
    id: 3,
    name: "Thịt ba chỉ nướng sa tế",
    img: require("./assets/IMG/home/thit-ba-chi-nuong-sate.png"),
    des: [
      " Món thịt ba chỉ nướng sa tế với màu sắc bắt",
      " mắt cùng mùi thơm nức mũi rất hấp dẫn",
      " mời gọi bất cứ ai vừa nhìn thấy nó. Những miếng",
      " thịt mềm thơm được nướng vừa chín tới",
      " thấm đều gia vị cùng vị cay cay của sa tế kích thích vị giác vô cùng.",
      " Bạn có thể ăn thịt ba chỉ nướng cùng với dưa leo, rau cải chấm muối ớt ",
      " chanh để cảm nhận trọn vẹn hương vị của món ăn.",
    ],
    type: "Đồ nướng",
  },
  {
    id: 4,
    name: "Súp cua bí đỏ",
    img: require("./assets/IMG/home/sup-cua-bi-do.png"),
    des: [
      " Súp cua bí đỏ sau khi hoàn thành có màu cam vàng ngon mắt",
      " mùi thơm nức đặc trưng của bí đỏ và cua. Ăn một miếng",
      " bạn có thể cảm nhận được thịt cua mềm ngọt, bí đỏ béo ngậy",
      " tan ngay trong miệng, rất hấp dẫn.",
    ],
    type: "Súp",
  },
  {
    id: 6,
    name: "Lẩu thái",
    img: require("./assets/IMG/home/lau-thai.png"),
    des: [
      " Vị chua chua, cay cay kích thích vị giác cộng với màu đỏ cam của ớt",
      " thơm, cà chua đủ tạo nên sự hấp dẫn cho món ăn này. Bạn có thể cảm nhận",
      " được bằng việc ăn với bún hoặc với các loại toping khác.",
    ],
    type: "Lẩu",
  },
  {
    id: 7,
    name: "Trà sữa kem trứng",
    img: require("./assets/IMG/home/tra-sua-kem-trung.png"),
    des: [
      " Nếu như trà sữa macchiato từng “gây nghiện” với giới trẻ",
      " thì món trà sữa kem trứng cũng được “săn đón” không kém.",
      " Lớp kem trứng béo ngậy, vị mằn mặn pha lẫn ngọt nhẹ vô cùng",
      " hợp khi uống cùng trà sữa mát lạnh.",
    ],
    type: "Thức uống",
  },
  {
    id: 8,
    name: "Nước ép cà rốt",
    img: require("./assets/IMG/home/nuoc-ep-ca-rot.png"),
    des: [
      " Nước ép cà rốt được ưa chuộng bởi hương vị thơm ngon",
      " và nhiều tác dụng tốt cho sức khỏe, đặc biệt là tốt cho đôi mắt và làn da.",
      " Cách làm nước ép cà rốt giữ trọn dinh dưỡng trở nên đơn giản hơn",
    ],
    type: "Thức uống",
  },
  {
    id: 10,
    name: "Bạch tuộc nướng sa tế",
    img: require("./assets/IMG/home/bach-tuot-nuong-sate.png"),
    des: [
      " Bạn chỉ cần làm sạch bạch tuộc rồi ướp cùng một chút hành tím",
      " tỏi băm nhuyễn, sa tế cà gia vị. Để ướp khoảng 30-40 phút cho bạch tuộc",
      " thấm đều gia vị là có thể mang đi nướng. Những miếng bạch tuộc vàng ươm,",
      " dai dai cùng vị cay của sa tế rất hấp dẫn.",
    ],
    type: "Đồ nướng",
  },
  {
    id: 11,
    name: "Súp hột vịt lộn",
    img: require("./assets/IMG/home/sup-hot-vit-lon.png"),
    des: [
      " Hột vịt lộn là thực phẩm cung cấp dinh dưỡng dồi dào.",
      " Bên cạnh những món truyền thống như hột vịt lộn luộc, lẩu hột vịt lộn,",
      " hột vịt lộn xào me,... thì súp hột vịt lộn cũng thơm ngon, hấp dẫn không kém.",
    ],
    type: "Súp",
  },
  {
    id: 12,
    name: "Lẩu hải sản",
    img: require("./assets/IMG/home/lau-hai-san.png"),
    des: [
      " Khi nhắc đến các loại lẩu phù hợp với mùa hè,",
      " bạn sẽ không thể nào bỏ qua được món lẩu hải sản chua cay.",
      " Món ăn này được nhiều tín đồ ẩm thực đánh giá cao vì trong quá,",
      " trình chế biến tận dụng được hương vị tươi ngon của các loại hải sản.",
    ],
    type: "Lẩu",
  },
  {
    id: 13,
    name: "Lẩu nấm",
    img: require("./assets/IMG/home/lau-nam.png"),
    des: [
      " Đối với những tín đồ thích ăn nấm, lẩu nấm chắc hẳn là món ăn",
      " chân ái của các bạn. Lẩu có vị chua chua của khóm, cay cay từ ớt và",
      " rất nhiều loại nấm giòn giòn, sực sực chắc hẳn là món ăn bạn không nên",
      " bỏ qua để giải nhiệt cho mùa hè này!",
    ],
    type: "Lẩu",
  },
  {
    id: 14,
    name: "Gà nướng mật ong",
    img: require("./assets/IMG/home/ga-nuong-mat-ong.png"),
    des: [
      " Gà nướng mật ong là một món ăn hấp dẫn mà bạn rất khó chối từ.",
      " Khi thưởng thức, bạn sẽ được cắn từng miếng thịt mềm mềm cùng hương vị",
      " đậm đà của nước sốt mật ong. Chấm với chút muối tiêu chanh ớt chua chua,",
      " cay cay thì càng tuyệt vời.",
    ],
    type: "Đồ nướng",
  },
  {
    id: 15,
    name: "Thịt xiên nướng rau củ",
    img: require("./assets/IMG/home/thit-xien-nuong-rau-cu.png"),
    des: [
      " Bữa tiệc nướng của bạn cùng gia đình sẽ không thể bỏ lỡ món thịt xiên",
      " nướng rau củ. Món ăn là sự kết hợp hài hòa giữa thịt bò cùng các loại rau",
      " củ như hành tây, ớt chuông, cà chua bi,... Khi thường thức, bạn sẽ không",
      " có cảm giác ngán bởi có rau củ đi kèm. ",
    ],
    type: "Đồ nướng",
  },
  {
    id: 16,
    name: "Sò huyết mỡ hành",
    img: require("./assets/IMG/home/hau-nuong-mo-hanh.png"),
    des: [
      "Nhắc đến các món nướng ngon đến từ hải sản thì không thể nào",
      " quên một món đặc biệt là sò huyết nướng mỡ hành. Món ăn này không",
      " chỉ thơm ngon mà còn bổ dưỡng rất tốt cho sức khỏe. Thịt sò huyết",
      " ngọt kết hợp cùng vị béo và mùi thơm của mỡ hành tạo nên món ăn ngon khó cưỡng.",
    ],
    type: "Đồ nướng",
  },
];

export default datahome;
