const datahome = [
  {
    id: 1,
    name: "Lẩu cá chép giòn",
    img: require("./assets/IMG/home/lau-ca-chep-gion-chua-ngot-hai-hoa.png"),
    des: [
      " Món ăn này được chế biến từ cá chép tươi sống",
      " được làm sạch và chiên giòn. Nước lẩu được nấu từ xương cá",
      " xương ống và các loại rau củ quả như cà chua, dứa, măng chua",
      " ... Lẩu cá chép giòn thường được ăn kèm với bún",
      " rau sống và các loại hải sản khác như tôm, cua, mực,...",
    ],
    nguyenlieu: [
      "- 4 lít nước xương hầm\n\n",
      "- 1 con cá chép giòn\n\n",
      "- 2 củ hành tây\n\n",
      "- 1 trái thơm\n\n",
      "- 3 quả cà chua\n\n",
      "- Rau ăn lẩu (chuẩn bị tùy theo khẩu phần của gia đình bạn):",
      " Nấm kim châm, bông thiên lý, cải xanh, mồng tơi.\n\n",
      "- Gia vị: Hành boa rô, sả, ngò gai, thì là, hạt nêm,",
      " đường trắng, nước mắm, sa tế cay, dầu ăn\n\n",
      "- Bún tươi",
    ],
    buoc1: [
      "- Cá rửa sạch, thái thành từng miếng mỏng vừa ăn,",
      " sau đó ướp với 1 muỗng hạt nêm.\n\n",
      "- Ép nước 1 quả thơm chung với 1 củ hành tây.",
      " 3 quả cà chua rửa sạch và xay nhuyễn.\n\n",
      "- Lấy 1 cây hành và 2 cây sả rửa sạch và băm nhuyễn.",
      " Ngò gai, thì là rửa sạch và cắt",
      " khúc khoảng 1-2cm.\n\n",
      "- Các rau còn lại rửa sạch để cho ráo nước.\n",
    ],
    buoc2: [
      "- Bật bếp để làm nóng nồi, sau đó bỏ 3 muỗng canh dầu ăn vào.",
      " Đợi dầu sôi, cho hành, sả vào phi cho thơm.\n\n",
      "- Hành, sả chín vàng thì tiếp tục cho cà chua vào xào đến khi chín nẫu,",
      " rồi nêm 2 muỗng hạt nêm, 2 muỗng đường trắng và sa tế vào nồi",
      " (khẩu phần tuỳ theo bạn ăn cay nhiều hay ít).\n\n",
      "- Đợi đến khi hỗn hợp sệt lại thì để đầu và xương cá vào xào cho thịt săn lại.",
      " Sau đó, đổ nước cốt thơm hành tây và nước xương hầm vào nồi.\n",
    ],
    buoc3: [
      "- Đậy nắp kín lại, đun cho tới khi nước dùng sôi lên thì để",
      " thả hành boa rô, thì là vào cho thơm.\n\n",
      "- Dọn kèm rau, bún ra cùng với lẩu và thưởng thức.\n",
    ],
    linkytb: "https://www.youtube.com/watch?v=1XnOkWdlUC4",
    type: "Lẩu",
  },
  {
    id: 2,
    name: "Cháo sườn",
    img: require("./assets/IMG/home/chao-suon.png"),
    des: [
      " Cháo sườn được nấu từ gạo và nước",
      " sau đó cho sườn heo vào ninh nhừ. Khi sườn chín mềm",
      " bạn cho các loại gia vị vào nêm cho vừa ăn. Cháo sườn thường",
      " được ăn kèm với hành lá",
      " rau răm, và các loại topping như quẩy, ruốc,...",
    ],
    nguyenlieu: [
      "- 300g sườn heo\n\n",
      "- 300g gạo\n\n",
      "- Rau ngò rí, hành lá, hành tím\n\n",
      "- Gia vị: hạt nêm, đường, muối, dầu ăn, tiêu\n\n",
    ],
    buoc1: [
      "- Sườn heo để nấu cháo sườn thì bạn nên chọn sườn loại có nhiều thịt một chút,",
      " mua về rửa sạch rồi cắt thành các miếng.\n\n",
      "- Gạo có thể chọn loại gạo tẻ hoặc gạo tẻ trộn với gạo nếp để nấu cho thơm và cháo không bị vữa.",
      " Vo sạch 300g gạo sau đó cho vào chén, ngâm gạo ngập nước trong khoảng 3 giờ đồng hồ để cho gạo mềm bớt.\n\n",
      " Ngâm xong để gạo ráo nước, rồi cho vào máy xay, xay nhỏ để nấu cháo nhanh hơn.",
      "- Lưu ý chỉ xay nhỏ vừa phải thôi nhé. Hành tím rửa sạch, bỏ vỏ rồi bào lát mỏng để phi thơm.",
      " Ngò rí rửa sạch rồi cắt nhuyễn. Hành lá rửa sạch,\n\n",
      " phần gốc cắt thành khúc dài khoảng 1cm, phần thân cắt nhuyễn.\n",
    ],
    buoc2: [
      "- Đặt nồi lên bếp rồi đổ nước vào nấu sôi.",
      "  Khi nước đã sôi thì cho sườn vào và luộc trong khoảng 2 phút để loại bỏ bọt bẩn,",
      " sau đó vớt sườn ra rồi rửa sơ lại với nước lạnh cho sạch hẳn.\n\n",
      "- Đặt nồi lên bếp và đổ vào khoảng 1 lít nước rồi nấu sôi.",
      " Khi nước đã sôi, bạn cho phần sườn đã luộc sơ khi nãy vào hầm, đậy nắp, lửa để vừa.",
      " Khi nồi sườn hầm được 30 phút thì vớt bỏ bọt nổi trên bề mặt để không làm nước bị đục,",
      " sau đó cho chén gạo vừa xay vào nồi. Khi nồi cháo đã sôi thì bạn",
      " vớt phần sườn ra ngoài để xé nhỏ thịt, không tắt bếp,",
      " vẫn tiếp tục nấu cháo để gạo nở ra thêm nhé!",
    ],
    buoc3: [
      "- Thịt xé thành các miếng nhỏ vừa ăn và bỏ đi phần xương,",
      " có thể lấy kéo cắt nhỏ ra nếu thịt còn nóng rồi xé cho dễ.",
      " Sau khi xé xong bạn cho vào lại nồi cháo rồi đảo đều.",
      " Nêm nếm theo khẩu vị vừa ăn rồi cho phần hành lá cắt khúc ban đầu vào nồi, sau đó tắt bếp.\n\n",
      "- Đặt chảo lên bếp và cho dầu ăn vào. Đợi dầu nóng lên rồi cho hành tím vào phi thơm.",
      " Phi cho đến khi hành tím vàng vừa tới, có mùi thơm là được.\n\n",
      "- Vậy là món cháo sườn đã được hoàn thành. Bạn múc cháo ra tô,",
      " cho hành lá, ngò rí, hành phi lên trên và rắc thêm 1 ít tiêu nữa",
      " là có thể dùng ngay được rồi. Món cháo sườn nên ăn lúc còn nóng bạn nhé.\n",
    ],
    linkytb: "https://www.youtube.com/watch?v=QtcCmgObWAg",
    type: "Cháo",
  },
  {
    id: 3,
    name: "Thịt ba chỉ nướng sa tế",
    img: require("./assets/IMG/home/thit-ba-chi-nuong-sate.png"),
    des: [
      " Món thịt ba chỉ nướng sa tế với màu sắc bắt",
      " mắt cùng mùi thơm nức mũi rất hấp dẫn",
      " mời gọi bất cứ ai vừa nhìn thấy nó. Những miếng",
      " thịt mềm thơm được nướng vừa chín tới",
      " thấm đều gia vị cùng vị cay cay của sa tế kích thích vị giác vô cùng.",
      " Bạn có thể ăn thịt ba chỉ nướng cùng với dưa leo, rau cải chấm muối ớt ",
      " chanh để cảm nhận trọn vẹn hương vị của món ăn.",
    ],
    nguyenlieu: [
      "- Ba chỉ bò (số lượng tùy thích)\n\n",
      "- 40g tỏi\n\n",
      "- 40g sả\n\n",
      "- 20ml siro ngô\n\n",
      "- 20g hành khô\n\n",
      "- 40g ớt xanh, đỏ\n\n",
      "- 40g ớt xanh, đỏ\n\n",
      "- 20g rễ rau mùi\n\n",
      "- Ăn kèm: rau mùi, hành tây, kim chi, xà lách (số lượng tùy thích)\n\n",
      "- Gia vị: sa tế, đường, nước tương, mật ong, nước mắm, hạt tiêu, hạt nêm.\n\n",
      "- Dụng cụ: máy xay (sinh tố), bếp nướng điện (hoặc có thể nướng bằng than)\n\n",
    ],
    buoc1: [
      "- Đầu tiên, bạn cho tỏi, sả, hành khô và rau mùi vào máy xay và xay nhuyễn.",
      " Sau đó, bạn cho hỗn hợp vừa xay vào chén cùng sa tế, 15ml mật ong,",
      " 20ml nước tương, 1/3 muỗng canh hạt nêm và 1/3 muỗng canh hạt tiêu.",
      " 3 quả cà chua rửa sạch và xay nhuyễn.",
      " Xong thì bạn trộn đều các nguyên liệu lại với nhau.",
      " Tiếp theo, bạn cắt hành tây và rau mùi thành những khúc vừa ăn nha.\n\n",
    ],
    buoc2: [
      "- Bạn cho vào chén khác 30ml nước mắm, 30g đường, nước cốt chanh, siro ngô,",
      " hỗn hợp vừa làm ở bước 1 và rau mùi cắt nhỏ. Bạn cũng trộn đều hỗn hợp này lại với nhau là được rồi nè.\n\n",
      "- Trước hết, bạn quét một lớp dầu ăn lên mặt bếp, rồi mới đặt ba chỉ bò vào.",
      " Trong quá trình nướng, bạn nên lật mặt bò qua lại,",
      " đồng thời, quét phần xốt sa tế lên thịt thường xuyên để thịt chín đều và thấm vị nhé.",
      "- Đợi đến khi hỗn hợp sệt lại thì để đầu và xương cá vào xào cho thịt săn lại.",
      " Bạn chỉ cần nướng đến khi thịt tỏa mùi thơm và vừa chín tới là được.\n",
    ],
    buoc3: [
      "- Món ba chỉ bò nướng sa tế hoàn thành là mùi thơm nức mũi lan tỏa khắp gian bếp luôn đấy.",
      " Từng thớ thịt tươi ngon, mềm thơm thấm đẫm xốt sa tế đậm vị, cay cay, nồng nồng,",
      " phải nói là cực đỉnh. Không chỉ thế, khi bạn ăn kèm hành tây, rau mùi,",
      " xà lách và kim chi chấm thêm nước xốt sa tế thì món ăn lại càng được phối trộn tinh tế",
      " hơn, “nâng cấp” hương vị tuyệt bậc luôn.\n\n",
    ],
    linkytb: "https://www.youtube.com/watch?v=bMkIQW8xfMo",
    type: "Đồ nướng",
  },
  {
    id: 4,
    name: "Súp cua bí đỏ",
    img: require("./assets/IMG/home/sup-cua-bi-do.png"),
    des: [
      " Súp cua bí đỏ sau khi hoàn thành có màu cam vàng ngon mắt",
      " mùi thơm nức đặc trưng của bí đỏ và cua. Ăn một miếng",
      " bạn có thể cảm nhận được thịt cua mềm ngọt, bí đỏ béo ngậy",
      " tan ngay trong miệng, rất hấp dẫn.",
    ],
    nguyenlieu: [
      "- 200g bí đỏ\n\n",
      "- 1 con cua biển\n\n",
      "- 1 bông cải trắng\n\n",
      "- 20g hành tây\n\n",
      "- 350ml nước dùng gà\n\n",
      "- 50ml kem sữa tươi\n\n",
      "- 30ml sữa tươi không đường\n\n",
      "- Gia vị: Bơ lạt, hạt nêm, muối",
    ],
    buoc1: [
      "- Cua sau khi mua về đừng vội cắt dây cột mà hãy chọc tiết cua trước.\n\n",
      "- Bạn lật ngửa yếm dưới bụng cua và lấy đầu kéo hoặc dao nhọn chọc thẳng",
      " vào phần hõm cho tới khi chân và càng đều duỗi thẳng.\n\n",
      "- Vệ sinh cua sạch rồi bạn bắc nồi hấp, bỏ cua vào hấp cho tới",
      " khi cua chín chuyển sang màu cam, gắp cua ra dĩa để nguội.\n\n",
      "- Kế đến, bạn tách mai cua ra dĩa trước để gạch không bị đổ ra ngoài,",
      " bỏ phần lông cua và lấy phần thịt.\n\n",
      "-- Mẹo hay: Khi luộc cua, bạn thêm vào ít nước để giữ độ ngọt.",
      " Chỉ nên cho một lượng nước xâm xấp mặt cua.\n\n",
      "- Cuối cùng bạn cắt 200g bí đỏ, 20g hành tây thành miếng nhỏ, tách 100g bông cải trắng.",
    ],
    buoc2: [
      "- Đầu tiên bạn bắc nồi nóng rồi đun chảy 15g bơ lạt. Tiếp đến bạn cho bí đỏ, hành tây,",
      " bông cải trắng vào xào 2 phút cho tới khi rau củ chín.\n\n",
      "- Sau khi xào chín rau củ, bạn cho tiếp 350ml nước dùng gà vào,",
      " nấu 15 phút cho rau củ thật chín mềm.\n\n",
      "- Rau củ chín bạn tắt bếp dùng máy xay cầm tay hoặc máy xay sinh tố để xay nhuyễn mịn nồi súp.\n\n",
      "- Cuối cùng cho thêm thịt cua và phần gạch đã tách ra cùng 1/2 muỗng hạt nêm, 50ml kem sữa tươi,",
      " 30ml sữa tươi không đường vào nồi, nấu ở lửa nhỏ thêm 2 phút cho nóng rồi múc ra chén.",
    ],
    buoc3: [
      "- Súp cua bí đỏ sau khi hoàn thành có màu cam vàng ngon mắt,",
      " mùi thơm nức đặc trưng của bí đỏ và cua.",
      " Ăn một miếng, bạn có thể cảm nhận được thịt cua mềm ngọt,",
      " bí đỏ béo ngậy, tan ngay trong miệng, rất hấp dẫn.",
    ],
    linkytb: "https://www.youtube.com/watch?v=LwCmy6CiRRs",
    type: "Súp",
  },
  {
    id: 6,
    name: "Lẩu thái",
    img: require("./assets/IMG/home/lau-thai.png"),
    des: [
      " Vị chua chua, cay cay kích thích vị giác cộng với màu đỏ cam của ớt",
      " thơm, cà chua đủ tạo nên sự hấp dẫn cho món ăn này. Bạn có thể cảm nhận",
      " được bằng việc ăn với bún hoặc với các loại toping khác.",
    ],
    nguyenlieu: [
      "- 3 bộ xương gà\n\n",
      "- 1 củ riềng\n\n",
      "- 20 nhánh sả\n\n",
      "- 20 củ hành khô\n\n",
      "- Me chín\n\n",
      "- Nấm hương\n\n",
      "- 500g lá mùi tàu\n\n",
      "- 1 trái bắp\n\n",
      "- Nước cốt dừa\n\n",
      "- Vài lá chanh\n\n",
      "- Gia vị: Đường, hạt nêm, muối, bột ngọt\n\n",
    ],
    buoc1: [
      "- Bạn chỉ cần lấy xương gà trần sơ qua với nước sôi,",
      " sau đó vớt xương gà ra rửa sạch lại một lần nữa.\n\n",
      "- Sau đó, bạn băm nhuyễn sả và cắt khúc vừa ăn khoảng 5cm.\n\n",
      "- Cắt riềng thành từng lát mỏng, hành khô bóc vỏ để nguyên củ.\n\n",
      "- Nấm hương rửa sạch rồi cắt đôi. Lá ngò gai rửa sạch, cắt làm 3 lát.\n\n",
      "- Ngâm me trong nước ấm rồi lọc lấy nước cốt.",
    ],
    buoc2: [
      "- Bạn cho xương gà, sả và riềng thái sợi vào nồi nước.",
      " Bật bếp lớn, đun sôi nước dùng xương gà rồi hạ lửa nhỏ,",
      " sau đó cho hành khô và nấm đông cô vào.\n\n",
      "- Sau đó, bạn cho nước cốt me vào đồng thời",
      " thêm vào 1 muỗng canh đường, 1 muỗng cà phê hạt nêm,",
      " 1 muỗng cà phê muối, 1 muỗng cà phê bột ngọt.\n\n",
    ],
    buoc3: [
      "- Bạn cắt bắp thành từng khúc dài 3 - 4cm rồi cho vào nồi lẩu để nước lẩu Thái được ngọt hơn.\n\n",
    ],
    linkytb: "https://www.youtube.com/watch?v=pSBwgYfoA00",
    type: "Lẩu",
  },
  {
    id: 7,
    name: "Trà sữa kem trứng",
    img: require("./assets/IMG/home/tra-sua-kem-trung.png"),
    des: [
      " Nếu như trà sữa macchiato từng “gây nghiện” với giới trẻ",
      " thì món trà sữa kem trứng cũng được “săn đón” không kém.",
      " Lớp kem trứng béo ngậy, vị mằn mặn pha lẫn ngọt nhẹ vô cùng",
      " hợp khi uống cùng trà sữa mát lạnh.",
    ],
    nguyenlieu: [
      "- 10g hồng trà nướng\n\n",
      "- 15g trà gạo\n\n",
      "- 60g bột sữa\n\n",
      "- 80ml kem béo\n\n",
      "- 80ml sữa tươi không đường\n\n",
      "- 100g bột trứng\n\n",
      "- Nước nóng\n\n",
      "- Gia vị: Đường\n\n",
      "- Dụng cụ: Rây lọc, ấm pha trà\n\n",
    ],
    buoc1: [
      "- Đầu tiên, bạn cho vào ấm 500 ml nước nóng, 10g hồng trà nướng,",
      " 15g trà gạo và khuấy đều rồi để ngâm ủ từ 15-20 phút cho ra chất trà.\n\n",
      "- Sau đó, bạn đổ trà ra ly lớn qua 1 cái rây để lọc bỏ bã trà.\n\n",
    ],
    buoc2: [
      "- Sau khi lọc xong bạn thu được khoảng 400 ml nước trà,",
      " cho vào nước trà 60g bột sữa, 60g đường rồi khuấy đều hỗn hợp thành trà sữa.",
      " Ở bước này bạn có thể gia giảm lượng đường cho phù hợp với khẩu vị.\n\n",
      "- Cho vào cối xay sinh tố 80 ml kem béo,",
      " 80 ml sữa tươi không đường cùng với 100g bột trứng rồi đem đi xay",
      " mịn ở mức độ vừa phải đến khi kem trứng mịn, có màu vàng là được.\n\n",
    ],
    buoc3: [
      "- Cho đá vào ly, sau đó rót trà sữa vào gần đầy miệng.",
      " Tiếp theo cho thêm kem trứng đã xay có màu vàng lên trên cùng.\n\n",
      "-- Mẹo hay: Bạn có thể thêm chút đường nâu lên trên mặt kem trứng,",
      " sau đó dùng dụng cụ khò lửa để hơ lửa trên bề mặt kem trứng có màu vàng hơi cháy hấp dẫn.",
    ],
    linkytb: "https://www.youtube.com/watch?v=7IOw1Km77GQ",
    type: "Thức uống",
  },
  {
    id: 8,
    name: "Nước ép cà rốt",
    img: require("./assets/IMG/home/nuoc-ep-ca-rot.png"),
    des: [
      " Nước ép cà rốt được ưa chuộng bởi hương vị thơm ngon",
      " và nhiều tác dụng tốt cho sức khỏe, đặc biệt là tốt cho đôi mắt và làn da.",
      " Cách làm nước ép cà rốt giữ trọn dinh dưỡng trở nên đơn giản hơn",
    ],
    nguyenlieu: [
      "- 1 củ cà rốt\n\n",
      "- Đường (tùy khẩu vị)\n\n",
      "- Nước đá đập nhuyễn (tùy sở thích)\n\n",
    ],
    buoc1: [
      "- Đầu tiên, rửa sạch các nguyên liệu với nước. Cà rốt đem gọt vỏ, xong rồi đem cắt chúng.\n\n",
    ],
    buoc2: [
      "- Cho cà rốt vào máy ép, ép đến khi ra hết nước thì bỏ phần xác hỗn hợp đi nhé.",
      " Nếu không có máy ép thì có thể dùng máy xay sinh tố.",
    ],
    buoc3: [
      "- Sau khi xay xong, ta lọc hỗn hợp qua rây hoặc vải mùng là đã xong rồi đấy.",
    ],
    linkytb: "https://www.youtube.com/watch?v=3QBLawH1x8U",
    type: "Thức uống",
  },
  {
    id: 10,
    name: "Bạch tuộc nướng sa tế",
    img: require("./assets/IMG/home/bach-tuot-nuong-sate.png"),
    des: [
      " Bạn chỉ cần làm sạch bạch tuộc rồi ướp cùng một chút hành tím",
      " tỏi băm nhuyễn, sa tế cà gia vị. Để ướp khoảng 30-40 phút cho bạch tuộc",
      " thấm đều gia vị là có thể mang đi nướng. Những miếng bạch tuộc vàng ươm,",
      " dai dai cùng vị cay của sa tế rất hấp dẫn.",
    ],
    nguyenlieu: [
      "- 500gr bạch tuộc\n\n",
      "- 2 cây sả\n\n",
      "- 2 tép tỏi\n\n",
      "- 1 trái ớt\n\n",
      "- Gia vị: Đường, muối, bột ngọt, sa tế, dầu điều\n\n",
    ],
    buoc1: [
      "- Phần bạch tuộc mua về bạn cần làm sạch rồi rửa lại với nước và để ráo.",
      " Đối với sả, ớt và tỏi thì bạn rửa sạch và băm nhỏ.\n\n",
      "-- Mẹo sơ chế: Để khử sạch nhớt và mùi tanh từ bạch tuộc bạn cần ngâm",
      " và rửa kỹ với muối rồi xả lại cùng nước lạnh.\n\n",
    ],
    buoc2: [
      "- Bạn cho bạch tuộc vào tô và ướp lần lượt với 1 muỗng đường,",
      " ½ muỗng bột ngọt, 2 muỗng sa tế, 1 muỗng màu điều cùng sả,",
      " ớt và tỏi đã băm nhuyễn ở bước trên.\n\n",
      "- Sau đó, bạn trộn đều và cho vào ngăn mát tủ lạnh,",
      " ướp bạch tuộc khoảng 30 phút cho thấm gia vị.\n\n",
      "- Bạn làm nóng bếp nướng điện trước khoảng",
      " 5 phút ở nhiệt độ 150 độ C, sau đó cho bạch tuộc lên nướng.\n\n",
      " Bạn nướng khoảng 10 phút đến khi thấy bạch tuộc lên màu đẹp",
      " và cảm nhận được độ dai giòn là bạch tuộc đã chín.\n\n",
      "- Ngoài ra, bạn cũng có thể nướng bạch tuộc trên bếp than đến",
      " khi vàng đều hai mặt thay cho bếp nướng điện đều được.",
    ],
    buoc3: [
      "- Món bạch tuộc nướng sa tế sẽ khiến nhiều người mê đắm bởi",
      " phần bạch tuộc nướng vừa chín tới nên vẫn giữ được độ giòn, ngọt, thấm đều gia vị.\n\n",
      "- Khi ăn bạn sẽ cảm nhận được sự hòa quyện đậm đà của sa tế, vị thơm của tỏi,",
      " sả và vị cay của ớt,... Tất cả sẽ tạo nên một món ăn thơm ngon, hài hòa, tròn vị.",
    ],
    linkytb: "https://www.youtube.com/watch?v=aRKSNXD8fiI",
    type: "Đồ nướng",
  },
  {
    id: 11,
    name: "Súp hột vịt lộn",
    img: require("./assets/IMG/home/sup-hot-vit-lon.png"),
    des: [
      " Hột vịt lộn là thực phẩm cung cấp dinh dưỡng dồi dào.",
      " Bên cạnh những món truyền thống như hột vịt lộn luộc, lẩu hột vịt lộn,",
      " hột vịt lộn xào me,... thì súp hột vịt lộn cũng thơm ngon, hấp dẫn không kém.",
    ],
    nguyenlieu: [
      "- 16 hột vịt lộn\n\n",
      "- 80 gram táo tàu\n\n",
      "- 80 gram táo đỏ\n\n",
      "- 25 gram kỷ tử\n\n",
      "- 1 lít nước súp gà đóng hộp\n\n",
      "- 1/4 củ gừng\n\n",
      "- Gia vị: muối, đường, hạt nêm, tiêu\n\n",
    ],
    buoc1: [
      "- Hột vịt lộn sau khi mua về,",
      " bạn đem đi rửa sạch. Sau đó, để hột vịt lộn vào nồi rồi cho nước",
      " vào đến khi ngập hết hột vịt lộn. Bật lửa và luộc trong vòng 15 phút kể từ khi nước sôi.\n\n",
      "- Sau khi hột vịt lộn đã chín, bạn vớt ra, để nguội và lột vỏ.",
      " Bạn nhớ giữ lại phần nước hột vịt lộn để nấu súp nhé!\n\n",
    ],
    buoc2: [
      "- Bạn ngâm táo tàu, táo đỏ, kỷ tử với nước trong khoảng 10 phút, sau đó vớt ra,",
      " rửa sạch với nước. Gừng cạo vỏ, rửa sạch rồi đem đi cắt sợi.\n\n",
      "- Rau răm rửa sạch rồi cắt thành từng khúc nhỏ.\n\n",
      "- Cho nước hầm gà đóng hộp vào nồi cùng 500ml nước,",
      " sau đó nêm vào 1,5 muỗng canh hạt nêm, 1 muỗng cà phê đường,",
      " nửa muỗng cà phê muối rồi khuấy cho tan.\n\n",
      "- Nấu nước súp đến khi vừa sôi thì cho táo tàu và táo đỏ vào.",
      "- Tiếp đến cho hết hột vịt lộn đã lột vỏ và phần nước hột vịt lộn,",
      " kỷ tử vào và nấu đến khi súp sôi thì tắt bếp.\n\n",
      "- Cho thêm gừng và rau răm để làm tăng hương thơm cho món ăn.",
    ],
    buoc3: [
      "- Món súp hột vịt lộn có màu sắc sặc sỡ của hột vịt, táo tàu,",
      " táo đỏ và kỷ tử vô cùng đẹp mắt.\n\n",
      "- Nước súp đậm đà, thanh ngọt tự nhiên nên rất dễ ăn.\n\n",
      "- Hột vịt thì thơm béo, kết hợp cùng vị ngọt của táo tàu,",
      " táo đỏ và vị cay cay của gừng và rau răm vô cùng hấp dẫn.\n\n",
      "- Khi thưởng thức súp hột vịt lộn, bạn cho vào một ít tiêu xay để kích thích vị giác.",
    ],
    linkytb: "https://www.youtube.com/watch?v=yaTmqIQT3uw",
    type: "Súp",
  },
  {
    id: 12,
    name: "Lẩu hải sản",
    img: require("./assets/IMG/home/lau-hai-san.png"),
    des: [
      " Khi nhắc đến các loại lẩu phù hợp với mùa hè,",
      " bạn sẽ không thể nào bỏ qua được món lẩu hải sản chua cay.",
      " Món ăn này được nhiều tín đồ ẩm thực đánh giá cao vì trong quá,",
      " trình chế biến tận dụng được hương vị tươi ngon của các loại hải sản.",
    ],
    nguyenlieu: [
      "- Các loại hải sản: Mực, tôm, nghêu\n\n",
      "- Thịt bò\n\n",
      "- Nấm rơm, 1/4 trái thơm, lá chanh, cà chua, sả, tỏi, hành tím, ớt, rau thơm\n\n",
      "- Gia vị: Gia vị nấu lẩu thái, dầu ăn, đường, muối\n\n",
      "- Các loại rau ăn kèm: Bún tươi, rau muống, bắp cải thảo, rau nhúc,...\n\n",
    ],
    buoc1: [
      "- Các loại hải sản, thịt bò rửa sạch cắt miếng vừa ăn,",
      " nấm rơm rửa sạch nếu nấm lớn thì cắt đôi.\n\n",
      "- Cà chua cắt múi cau, sả, ớt, hành tím băm nhỏ.\n\n",
      "- Các loại rau ăn kèm bỏ các phần già, bẻ khúc vừa ăn.",
    ],
    buoc2: [
      "- Để món lẩu thái chua cay ngon bạn nên chuẩn bị nồi nước,",
      " sử dụng xương ống hầm trong khoảng 2 tiếng để lấy nước ngọt.\n\n",
      "- Chuẩn bị 1 cái nồi, cho sả, hành tím, ớt, cà chua và đảo đều cho",
      " thơm rồi cho nước hầm xương vào, nước sôi thì cho gói gia vị nấu lẩu thái,",
      " nêm nếm lại cho vừa ăn là đã có ngay nồi nước lẩu thái thơm ngon rồi.\n\n",
    ],
    buoc3: [
      "- Trước khi ăn, bỏ nấm rơm vào cho nấm chín, các loại hải sản,",
      " thịt bò ăn tới đâu nhúng tới đó.\n\n",
      "- Vị chua cay của nước lẩu hòa quyện với vị ngọt từ hải sản khi",
      " ăn kèm với bún là rất hấp dẫn luôn đó nha.",
    ],
    linkytb: "https://www.youtube.com/watch?v=mLPMIUFyARU",
    type: "Lẩu",
  },
  {
    id: 13,
    name: "Lẩu nấm",
    img: require("./assets/IMG/home/lau-nam.png"),
    des: [
      " Đối với những tín đồ thích ăn nấm, lẩu nấm chắc hẳn là món ăn",
      " chân ái của các bạn. Lẩu có vị chua chua của khóm, cay cay từ ớt và",
      " rất nhiều loại nấm giòn giòn, sực sực chắc hẳn là món ăn bạn không nên",
      " bỏ qua để giải nhiệt cho mùa hè này!",
    ],
    nguyenlieu: [
      "- 2 khúc mía lau\n\n",
      "- 1 trái bắp Mỹ\n\n",
      "- 1 cây hành baro (hành lá)\n\n",
      "- 1/2 củ cà rốt\n\n",
      "- 1/2 củ khoai môn\n\n",
      "- 1 cây bông cải xanh\n\n",
      "- Đậu hủ non, tàu hủ ky chiên\n\n",
      "- Nấm ăn kèm: nấm kim châm, nấm bào ngư, nấm đùi gà, nấm đông cô tươi,",
      " nấm linh chi tươi, nấm mỡ, nấm rơm\n\n",
      "- Dùng chung với: mì hoặc bún\n\n",
      "- Gia vị: đường, muối, hạt nêm, nước tương, dầu ăn, bột ngọt\n\n",
    ],
    buoc1: [
      "- Mía lau sau khi mua về rửa sạch để loại bỏ lớp dơ bên ngoài, gọt vỏ, chẻ ra làm đôi.\n\n",
      "- Bắp sau khi mua về lột bỏ vỏ và râu bắp, rửa sạch, rồi cắt làm hai khúc, sau đó chẻ đôi.\n\n",
      "- Cà rốt gọt vỏ, rửa sạch, cắt cạnh để tỉa bông, rồi cắt thành từng khoanh.\n\n",
      "- Với bông cải xanh, cắt nhỏ thành từng miếng vừa ăn, rồi sau đó rửa sạch với nước.\n\n",
      "- Đậu hủ non cắt khoanh nhỏ, tàu hủ ky cũng cắt thành từng miếng nhỏ vừa ăn.\n\n",
      "- Đối với những nấm ăn kèm bạn đem đi rửa sạch, để vào trong rổ cho ráo nước,",
      " rồi cắt thành từng miếng vừa ăn.\n\n",
      "- Khoai môn gọt vỏ, rửa sạch, cắt thành từng miếng vừa ăn.\n\n",
      " Sau đó, chiên cho vàng đều hết các mặt, việc chiên khoai môn",
      " trước khi để vào nồi sẽ làm món lẩu thơm ngon hơn.\n\n",
      "- Hành baro cắt xéo, rồi chia làm 2 phần, một phần để vào chén nhỏ.\n\n",
      "- Phần còn lại đem đi băm nhuyễn, sau đó cho lên chảo dầu nóng, phi lên cho vàng thơm.\n\n",
    ],
    buoc2: [
      "- Cho nước vào nồi cùng với bắp và mía lau,",
      " bắc lên bếp với lửa vừa, nấu khoảng 30 phút cho bắp và mía ra hết chất ngọt.\n\n",
      "- Sau 30 phút vớt bắp và mía lau ra, cho khoai môn, cà rốt, bông cải xanh,",
      " hành boaro vào. Rồi nêm nếm với một ít muối, đường,",
      " bột ngọt và nước tương cho vừa ăn, việc nêm với một ít nước tương sẽ làm",
      " tăng hương vị thơm ngon của món ăn.",
    ],
    buoc3: [
      "- Sau đó cho nấm vào nấu 3 - 5 phút cho nấm vừa chín tới là được,",
      " cuối cùng bạn cho đậu hủ non, tàu hủ ky và phần hành baro đã phi vào, rồi tắt  bếp.\n\n",
      "- Vậy là lẩu nấm chay đã hoàn thành rồi, cho lẩu lên bàn ăn và thưởng thức thôi.\n\n",
    ],
    linkytb: "https://www.youtube.com/watch?v=-neKwXGbYM0",
    type: "Lẩu",
  },
  {
    id: 14,
    name: "Gà nướng mật ong",
    img: require("./assets/IMG/home/ga-nuong-mat-ong.png"),
    des: [
      " Gà nướng mật ong là một món ăn hấp dẫn mà bạn rất khó chối từ.",
      " Khi thưởng thức, bạn sẽ được cắn từng miếng thịt mềm mềm cùng hương vị",
      " đậm đà của nước sốt mật ong. Chấm với chút muối tiêu chanh ớt chua chua,",
      " cay cay thì càng tuyệt vời.",
    ],
    nguyenlieu: [
      "- 6 đùi gà tỏi\n\n",
      "- Hành tím, ớt, chanh\n\n",
      "- Gia vị: Dầu hào, tiêu trắng, hạt nêm, giấm ăn, mật ong, muối,",
      "bột tỏi, ớt bột, đường, nước mắm, tiêu hạt\n\n",
    ],
    buoc1: [
      "- Đùi gà sau khi mua về thì bạn cho vào tô lớn,",
      " thêm 1 muỗng canh giấm và ít muối rồi xoa bóp kĩ.\n\n",
      "- Tiếp đến bạn rửa thật sạch lại với nước, để ráo.\n\n",
      "- Hành tím bạn bóc vỏ, rửa sạch rồi băm nhuyễn.\n\n",
    ],
    buoc2: [
      "- Bạn cho đùi gà vào tô lớn, thêm vào 1 muỗng cà phê muối,",
      " 1 ít tiêu trắng, 1 muỗng canh dầu hào, 2 muỗng canh mật ong,",
      " 1 muỗng cà phê bột tỏi, hành tím đã băm nhỏ vào trộn đều.\n\n",
      "- Bạn cho vào ngăn mát tủ lạnh khoảng 2 tiếng để gà thấm gia vị.\n\n",
      "- Bạn lấy giấy bạc lót vào khay nướng với lò nướng bật 200 độ C,",
      " tiếp đến bỏ phần gà đã ướp trên vào lò.\n\n",
      "- Sau khi nướng gà tầm 10 - 15 phút, bạn phết hỗn hợp gia vị lên",
      " gà để gà có màu đẹp mắt và thơm hơn.\n\n",
      "- Nướng trong vòng 45 phút (hoặc chênh lệch tùy vào khối lượng gà).\n\n",
    ],
    buoc3: [
      "- Bạn cho vào chén 1 muỗng canh đường, 2 muỗng canh nước cốt chanh,",
      " 2 muỗng cà phê hạt nêm, 1 muỗng canh ớt bột, 1/2 muỗng canh tiêu hạt,",
      " 1/2 muỗng canh nước mắm, 1 quả ớt cắt nhỏ, rồi khuấy đều cho hỗn hợp tan.\n\n",
      "- Gà nướng mật ong ngon là thịt gà phải nướng chín đều,",
      " bên ngoài lớp da phải có màu vàng óng ả của mật ong.\n\n",
      "- Hơn nữa, thịt gà phải có mùi thơm cũng như thấm vị thật đậm đà mới là ngon.",
    ],
    linkytb: "https://www.youtube.com/watch?v=5zwkm67dYio",
    type: "Đồ nướng",
  },
  {
    id: 15,
    name: "Thịt xiên nướng rau củ",
    img: require("./assets/IMG/home/thit-xien-nuong-rau-cu.png"),
    des: [
      " Bữa tiệc nướng của bạn cùng gia đình sẽ không thể bỏ lỡ món thịt xiên",
      " nướng rau củ. Món ăn là sự kết hợp hài hòa giữa thịt bò cùng các loại rau",
      " củ như hành tây, ớt chuông, cà chua bi,... Khi thường thức, bạn sẽ không",
      " có cảm giác ngán bởi có rau củ đi kèm. ",
    ],
    nguyenlieu: [
      "- 500g thịt nạc vai\n\n",
      "- 2 quả ớt chuông xanh và ớt chuông đỏ\n\n",
      "- 1/2 quả thơm\n\n",
      "- 2 củ hành tây\n\n",
      "- 50g sả và tỏi băm nhuyễn\n\n",
      "- Gia vị: muối, đường, hạt nêm, sa tế, dầu ăn, tiêu xay\n\n",
      "- Que tre\n\n",
    ],
    buoc1: [
      "- Thịt nạc rửa sạch với nước muối pha loãng. Cắt miếng nhỏ vừa ăn.\n\n",
      "- Ớt chuông, hành tây và thơm rửa sạch, cắt miếng vừa như thịt heo.\n\n",
      "- Que tre ngâm trong nước nóng khoảng 30 phút trước khi xiên thịt.\n\n",
    ],
    buoc2: [
      "- Đựng thịt heo vào tô lớn, cho thêm tỏi, sả đã băm nhuyễn, muối,",
      " đường, hạt nêm, sa tế, dầu ăn, tiêu xay và trộn thật đều thịt heo.\n\n",
      "- Cách ướp thịt nướng ngon là bạn nên để khoảng 1 giờ để thịt heo ngấm gia vị.\n\n",
      "- Dùng que tre xiên thịt heo đã ướp gia vị, ớt chuông xanh và đỏ,",
      " củ hành tây lần lượt xen kẽ với nhau cho đẹp mắt.\n\n",
      "- Nước ướp thịt còn lại phết lên ớt và hành tây để món ăn thêm ngon.\n\n",
      "- Chuẩn bị bếp than hồng, khi bếp than nóng, cho xiên thịt lên trên vỉ.\n\n",
      "- Nhớ trở đều tay để thịt chín đều và không bị khét.",
    ],
    buoc3: [
      "- Khi thịt đã chín đều các mặt bạn cho ra đĩa, và mời mọi người thưởng thức nhé.",
    ],
    linkytb: "https://www.youtube.com/watch?v=n4kOCDi9saA",
    type: "Đồ nướng",
  },
  {
    id: 16,
    name: "Sò huyết mỡ hành",
    img: require("./assets/IMG/home/hau-nuong-mo-hanh.png"),
    des: [
      "Nhắc đến các món nướng ngon đến từ hải sản thì không thể nào",
      " quên một món đặc biệt là sò huyết nướng mỡ hành. Món ăn này không",
      " chỉ thơm ngon mà còn bổ dưỡng rất tốt cho sức khỏe. Thịt sò huyết",
      " ngọt kết hợp cùng vị béo và mùi thơm của mỡ hành tạo nên món ăn ngon khó cưỡng.",
    ],
    nguyenlieu: [
      "- 1kg sò huyết\n\n",
      "- 5 nhánh hành lá\n\n",
      "- 50g tóp mỡ\n\n",
      "- 2 trái ớt\n\n",
      "- 3 tép tỏi\n\n",
      "- 1 quả chanh tươi\n\n",
      "- 50g đậu phộng rang\n\n",
      "- Gia vị: Đường, muối, giấm, nước mắm, bột ngọt\n\n",
    ],
    buoc1: [
      "- Đầu tiên, bạn đem sò huyết đem đi rửa sạch với nước nhiều",
      " lần đến khi thấy nước trong thì dừng, rồi mang sò đem ngâm",
      " với nước muối pha loãng và vài lát ớt trong 2 - 3 tiếng cho sò há miệng, nhả ra các chất bẩn.\n\n",
      "- Sau đó bạn đổ sò huyết vào nồi, cho ít nước luộc qua 5 phút",
      " cho sò hé miệng thì vớt ra để ráo nước, rồi bạn tách bỏ 1 bên vỏ.\n\n",
      "- Còn hành lá bạn mang rửa sạch, cắt thật nhỏ. Tỏi mang đi bóc vỏ và",
      " rửa với nước sạch, đậu phộng rang giã nát.\n\n",
    ],
    buoc2: [
      "- Kế tiếp, bạn bắc chảo lên bếp, cho 50g tóp mỡ vào đun cho mỡ chảy",
      " ra thì cho vào hành lá cắt nhỏ, thêm vào 1 muỗng cà phê muối,",
      " 1 muỗng cà phê bột ngọt thì đổ ra chén.\n\n",
      "- Tiếp theo, bạn cho tỏi và ớt vào chén, dùng chày giã nát tỏi ớt,",
      " rồi thêm vào 1 muỗng canh đường, 1 muỗng canh nước mắm và vắt một nửa quả chanh,",
      " khuấy đều lên cho hỗn hợp hòa tan với nhau.\n\n",
    ],
    buoc3: [
      "- Bạn chuẩn bị than hồng, đặt vỉ nướng lên, rồi xếp từng con sò lên vỉ",
      " và múc từng muỗng mỡ hành lên bề mặt từng con, nướng chừng 10 phút là",
      " bạn có thể thưởng thức món sò huyết này rồi.",
    ],
    linkytb: "https://www.youtube.com/watch?v=2IA7A5XKgV8",
    type: "Đồ nướng",
  },
];

export default datahome;
